version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    time: "07:00"
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 99
  reviewers:
  - TwoDCube
  assignees:
  - TwoDCube
  versioning-strategy: widen
  ignore:
  - dependency-name: friendsofphp/php-cs-fixer
    versions:
    - 2.18.1
    - 2.18.2
    - 2.18.3
    - 2.18.4
    - 2.18.5
  - dependency-name: backpack/crud
    versions:
    - 4.1.30
    - 4.1.31
    - 4.1.32
    - 4.1.33
    - 4.1.34
    - 4.1.36
    - 4.1.37
    - 4.1.38
    - 4.1.40
    - 4.1.41
  - dependency-name: filp/whoops
    versions:
    - 2.11.0
    - 2.12.0
    - 2.9.2
  - dependency-name: phpunit/phpunit
    versions:
    - 9.5.1
    - 9.5.2
    - 9.5.3
  - dependency-name: backpack/permissionmanager
    versions:
    - 6.0.4
    - 6.0.5
  - dependency-name: backpack/generators
    versions:
    - 3.1.5
    - 3.1.6
    - 3.1.7
  - dependency-name: backpack/pagemanager
    versions:
    - 3.0.6
    - 3.0.7
  - dependency-name: nunomaduro/collision
    versions:
    - 5.2.0
    - 5.3.0
  - dependency-name: laravel/tinker
    versions:
    - 2.5.0
    - 2.6.0
  - dependency-name: laravel/framework
    versions:
    - 7.30.3
  - dependency-name: laravel/helpers
    versions:
    - 1.4.0
